name: Value Sets Compression
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Download and compress value sets
        run:  (cd valuesets ; sh build.sh)
      - name: Make compressed value sets available as JSON
        uses: actions/upload-artifact@v2
        with:
          name: compressed-valueSets.json
          path: ${{ github.workspace }}/valuesets/compressed-valueSets.json

